# Fold 1
path: /media/chs.gpu/DATA/hdd/chs.data/research-cancerPathology/capstone_project/object-detection/benchmarking/datasets/NuCLSQC/v2/fold_1 # dataset root dir
train: train/images  
val: val/images  
test: test/images 
names: 
  0: 'cell'
